### ISSUE TITLE
Update large ensemble collection on glade

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/intake-esm-datastore#48]
looking at [cesm1-le-collection.yml](https://github.com/NCAR/intake-esm-datastore/blob/7fe7dd6/collection-input/cesm1-le-collection.yml), the existing collection is missing the RCP-4.5 dataset and can also take advantage of the `ctrl_experiment` / `ctrl_member_id` fields we recently added to the legacy `intake-esm` used to go from yaml -> netcdf (ahead of the netcdf -> csv conversion).

I'll update the yaml as well as the json / csv in a coming PR.

**Comment by matt-long** [comment]
The json file will need to be updated to include these additional field.

**Comment by mnlevy1981** [comment]
Rather than continue here, resolution to #64 will address this issue
