### ISSUE TITLE
Potential typo in cesm-le input definition

### ISSUE THREAD

**Issue by andersy005** [NCAR/intake-esm-datastore#6]
@matt-long, I saw this a while ago, and I meant to ask you whether the `member_id` is 0 or 5??

https://github.com/NCAR/intake-esm-datastore/blob/a706bee2de3efd1c1fca783ec8349c0b9f9d120a/collection-definitions/cesm1-le-collection.yml#L18-L21

**Comment by matt-long** [comment]
I think 0 is ok. There's only one member.
