### ISSUE TITLE
Error accessing GLADE CMIP5 catalog

### ISSUE THREAD

**Issue by edwardpmorris** [NCAR/intake-esm-datastore#60]
Hi, i get an error when trying to open the GLADE CMIP5 catalog, maybe the `catalog_file` path in the JSON needs updating? :

```
import intake
import intake_esm
url = "https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/glade-cmip5.json"
col = intake.open_esm_datastore(url)
col
```

`FileNotFoundError: [Errno 2] No such file or directory: '/glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip5.csv.gz'`

**Comment by andersy005** [comment]
Thank you for opening the issue, @edwardpmorris! Are you running this on one of the NCAR's machines i.e. Casper/DAV or Cheyenne?

**Comment by mnlevy1981** [comment]
I was able to access the file via `casper`, and it looks like permissions are okay on file (and the `catalogs/` directory):

```
$ ls -l /glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip5.csv.gz
-rw-rw-r-- 1 abanihi cmipdata 3189244 Oct 21 11:28 /glade/collections/cmip/catalog/intake-esm-datastore/catalogs/glade-cmip5.csv.gz
```

**Comment by edwardpmorris** [comment]
No was running examples in CoLab. I came to the example via pangeo, began following the intake-esm python package documentation examples (CMIP6), looked in the repo. for more catalogs, and wanted to take a look at the CMIP5 netcdf catalog. In the long run I would like to do calculations with CMIP5 data. Sorry I did not realise that it needs to be run from a specific machine. Guess I should have read up more, my mistake, happy to close this.

**Comment by andersy005** [comment]
If you still want to **explore the CMIP5 netcdf catalog (without loading the data)**  outside of NCAR's machines, you can download the json file: https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/glade-cmip5.json to your system and update the catalog_file entry with https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/glade-cmip5.json:

https://github.com/NCAR/intake-esm-datastore/blob/0cee23e72a089ace65bc6b7fa5ae999bd77ddc61/catalogs/glade-cmip5.json#L5

Once this is done, running 

```python
import intake
url = "PATH_TO_glade-cmip5.json"
col = intake.open_esm_datastore(url)
```

should work.
