### ISSUE TITLE
How to pick latest version when ingesting open_esm_datastore on .json url?

### ISSUE THREAD

**Issue by Recalculate** [NCAR/intake-esm-datastore#77]
Hi all, 

I understand there is a flag that can be used to ensure that you only ingest the latest version of files in a cmip6 catalogue.  My query is how to apply it when ingesting from a .json store, eg: 
`col_url='https://raw.githubusercontent.com/NCAR/intake-esm-datastore/master/catalogs/pangeo-cmip6.json'
col = intake.open_esm_datastore(col_url)`

How can you apply the --pick-latest-version flag to the above?

Many thanks.

**Comment by andersy005** [comment]
@Recalculate, do you mind opening this issue in https://github.com/intake/intake-esm? This is more of an intake-esm usage question. I will reply once this is in intake-esm.

**Comment by andersy005** [comment]
Superseded by https://github.com/intake/intake-esm/issues/262
